-- this script to create a table
CREATE TABLE IF NOT EXISTS users (
	id INT NOT NULL AUTO_INCEREMENT PRIMARY KEY,
	email VARCHAR(255) NOT NULL UNIQUE,
	name VARCHAR(255),
	country=US CO TN NOT NULL
);
